apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-converter-app
  namespace: exam-converter
  labels:
    app: exam-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exam-converter
  template:
    metadata:
      labels:
        app: exam-converter
    spec:
      containers:
      - name: exam-converter
        image: your-dockerhub-username/exam-converter:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: "production"
      imagePullPolicy: Always
      restartPolicy: Always