apiVersion: v1
kind: Service
metadata:
  name: exam-converter-service
  namespace: exam-converter
  labels:
    app: exam-converter
spec:
  selector:
    app: exam-converter
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP